### ISSUE TITLE
Code for training and testing with baseline methods

### ISSUE THREAD

**Issue by zhikaili** [ShengdingHu/GraphPolicyNetworkActiveLearning#1]
Hi,

Thank you for the paper and code. May I ask if you can release the code of training and testing with the baseline methods, e.g., CoreSet? Thank you!

**Comment by ShengdingHu** [comment]
Codes for the baselines are all in this repo already. By using different query strategies in src/test.py (e.g add parameter --method 6 to use the sixth method, which is Coreset) you can test different baseline methods

**Comment by zhikaili** [comment]
> Codes for the baselines are all in this repo already. By using different query strategies in src/test.py (e.g add parameter --method 6 to use the sixth method, which is Coreset) you can test different baseline methods

I see! Thank you very much. Nice work!
